"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

const API_BASE = process.env.NEXT_PUBLIC_SENTINEL_API_BASE_URL ?? "http://127.0.0.1:8080";

type EvidenceRef = { event_id: string; relevance: string };
type DetectionRef = { detection_id: string; relevance: string };

type AssessmentContent = {
  classification: string;
  confidence: number;
  summary: string;
  affected_assets: string[];
  evidence_refs: EvidenceRef[];
  detection_refs: DetectionRef[];
  hypotheses: string[];
  recommended_investigation_steps: string[];
  attack_techniques: string[];
  recommended_playbook_id: string | null;
  limitations: string[];
};

type Assessment = {
  assessment_id: string;
  incident_id: string;
  created_at: string;
  model_name: string;
  model_provider: string;
  prompt_version: string;
  validation_status: "VALID" | "REJECTED_SCHEMA" | "REJECTED_HALLUCINATION" | "TIMEOUT" | "PROVIDER_ERROR";
  assessment: AssessmentContent | null;
  latency_ms: number | null;
  error: string | null;
};

type AIStatus = {
  ai_enabled: boolean;
  provider: string;
  model: string;
  status: "READY" | "LOADING" | "DEGRADED" | "DISABLED";
  last_latency_ms: number | null;
};

function StatusBadge({ status }: { status: string }) {
  const color =
    status === "READY" || status === "VALID"
      ? "text-emerald-600 dark:text-emerald-400"
      : status === "DISABLED" || status === "LOADING"
        ? "text-zinc-500"
        : "text-red-600 dark:text-red-400";
  return <span className={`font-mono text-xs ${color}`}>{status}</span>;
}

export function AIAnalystPanel({
  incidentId,
  initialAssessment,
  initialAssessmentCount,
}: {
  incidentId: string;
  initialAssessment: Assessment | null;
  initialAssessmentCount: number;
}) {
  const [aiStatus, setAiStatus] = useState<AIStatus | null>(null);
  const [assessment, setAssessment] = useState<Assessment | null>(initialAssessment);
  const [assessmentCount, setAssessmentCount] = useState(initialAssessmentCount);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch(`${API_BASE}/api/v1/ai/status`, { cache: "no-store" })
      .then((r) => (r.ok ? r.json() : null))
      .then(setAiStatus)
      .catch(() => setAiStatus(null));
  }, []);

  async function handleAnalyze() {
    setBusy(true);
    setError(null);
    try {
      const res = await fetch(`${API_BASE}/api/v1/incidents/${incidentId}/ai/analyze`, {
        method: "POST",
      });
      if (res.status === 503) {
        setError("AI Analyst is not enabled on this deployment.");
        return;
      }
      if (!res.ok) throw new Error(`${res.status}`);
      const result = (await res.json()) as Assessment;
      setAssessment(result);
      setAssessmentCount((c) => c + 1);
    } catch {
      setError("Analysis request failed - the deterministic incident data above is unaffected.");
    } finally {
      setBusy(false);
    }
  }

  return (
    <section className="rounded-lg border-2 border-indigo-300 bg-indigo-50/40 p-4 dark:border-indigo-800 dark:bg-indigo-950/20">
      <div className="mb-1 flex items-center justify-between">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-indigo-700 dark:text-indigo-300">
          AI Assessment — Model Interpretation
        </h2>
        {aiStatus && <StatusBadge status={aiStatus.status} />}
      </div>
      <p className="mb-3 text-xs text-indigo-700/70 dark:text-indigo-300/70">
        Generated by a local model reading the evidence above. Advisory only — it cannot change any
        incident field, detection, or MissionNet state. Treat it as a second opinion, not a fact.
      </p>

      {aiStatus && !aiStatus.ai_enabled && (
        <p className="text-sm text-zinc-500">
          NOT ENABLED — set SENTINEL_AI_ENABLED=true and SENTINEL_LLM_PROVIDER=mlx to turn on the
          local AI Analyst (see RUNBOOK.md).
        </p>
      )}

      {aiStatus && aiStatus.ai_enabled && (
        <div className="mb-3 flex items-center gap-3">
          <button
            onClick={handleAnalyze}
            disabled={busy}
            className="rounded bg-indigo-700 px-3 py-1.5 text-xs font-medium text-white disabled:opacity-50 dark:bg-indigo-500"
          >
            {busy ? "Analyzing… (local model, may take up to a minute)" : "ANALYZE WITH LOCAL AI"}
          </button>
          <span className="font-mono text-[10px] text-zinc-500">
            {aiStatus.provider} · {aiStatus.model}
          </span>
          {assessmentCount > 0 && (
            <span className="text-[10px] text-zinc-500">
              {assessmentCount} assessment{assessmentCount === 1 ? "" : "s"} on record
            </span>
          )}
        </div>
      )}

      {error && <p className="mb-2 text-xs text-red-600 dark:text-red-400">{error}</p>}

      {assessment && (
        <div className="rounded border border-indigo-200 bg-white p-3 text-sm dark:border-indigo-900 dark:bg-black">
          <div className="mb-2 flex flex-wrap items-center gap-x-4 gap-y-1 text-[10px] text-zinc-500">
            <span>{new Date(assessment.created_at).toLocaleString()}</span>
            <span className="font-mono">{assessment.model_name}</span>
            <span className="font-mono">prompt {assessment.prompt_version}</span>
            {assessment.latency_ms !== null && <span>{assessment.latency_ms} ms</span>}
            <StatusBadge status={assessment.validation_status} />
          </div>

          {assessment.validation_status !== "VALID" && (
            <p className="text-xs text-red-600 dark:text-red-400">
              This analysis attempt was rejected and is not shown as evidence:{" "}
              {assessment.error ?? assessment.validation_status}
            </p>
          )}

          {assessment.assessment && (
            <>
              <div className="mb-2 flex items-center gap-3">
                <span className="rounded bg-indigo-100 px-2 py-0.5 text-xs font-semibold uppercase text-indigo-800 dark:bg-indigo-900 dark:text-indigo-200">
                  {assessment.assessment.classification}
                </span>
                <span className="text-xs text-zinc-500">
                  confidence {(assessment.assessment.confidence * 100).toFixed(0)}%
                </span>
              </div>
              <p className="mb-3">{assessment.assessment.summary}</p>

              {assessment.assessment.hypotheses.length > 0 && (
                <div className="mb-2">
                  <p className="text-xs font-semibold uppercase text-zinc-500">Hypotheses</p>
                  <ul className="list-inside list-disc text-xs">
                    {assessment.assessment.hypotheses.map((h, i) => (
                      <li key={i}>{h}</li>
                    ))}
                  </ul>
                </div>
              )}

              {assessment.assessment.recommended_investigation_steps.length > 0 && (
                <div className="mb-2">
                  <p className="text-xs font-semibold uppercase text-zinc-500">
                    Recommended Investigation Steps
                  </p>
                  <ul className="list-inside list-disc text-xs">
                    {assessment.assessment.recommended_investigation_steps.map((s, i) => (
                      <li key={i}>{s}</li>
                    ))}
                  </ul>
                </div>
              )}

              {assessment.assessment.evidence_refs.length > 0 && (
                <div className="mb-2">
                  <p className="text-xs font-semibold uppercase text-zinc-500">Cited Evidence</p>
                  <ul className="text-xs">
                    {assessment.assessment.evidence_refs.map((r) => (
                      <li key={r.event_id}>
                        <Link
                          href={`/events/${r.event_id}`}
                          className="font-mono text-blue-600 hover:underline dark:text-blue-400"
                        >
                          {r.event_id}
                        </Link>{" "}
                        — {r.relevance}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {assessment.assessment.detection_refs.length > 0 && (
                <div className="mb-2">
                  <p className="text-xs font-semibold uppercase text-zinc-500">Cited Detections</p>
                  <ul className="text-xs">
                    {assessment.assessment.detection_refs.map((r) => (
                      <li key={r.detection_id}>
                        <span className="font-mono">{r.detection_id}</span> — {r.relevance}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {assessment.assessment.attack_techniques.length > 0 && (
                <p className="mb-2 font-mono text-xs text-zinc-500">
                  ATT&amp;CK candidates: {assessment.assessment.attack_techniques.join(", ")}
                </p>
              )}

              <p className="mb-2 text-xs text-zinc-500">
                Recommended playbook:{" "}
                {assessment.assessment.recommended_playbook_id ?? "none (no playbook catalog yet)"}
              </p>

              {assessment.assessment.limitations.length > 0 && (
                <div>
                  <p className="text-xs font-semibold uppercase text-zinc-500">Limitations</p>
                  <ul className="list-inside list-disc text-xs text-zinc-500">
                    {assessment.assessment.limitations.map((l, i) => (
                      <li key={i}>{l}</li>
                    ))}
                  </ul>
                </div>
              )}
            </>
          )}
        </div>
      )}

      {!assessment && aiStatus?.ai_enabled && (
        <p className="text-xs text-zinc-500">No analysis has been run for this incident yet.</p>
      )}
    </section>
  );
}
