"""initial demo control schema

Revision ID: dff8d1615b41
Revises: 
Create Date: 2026-09-06 14:11:13.906147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dff8d1615b41'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('scenario_version', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('step_results', sa.JSON(), nullable=False),
    sa.Column('timeline', sa.JSON(), nullable=False),
    sa.Column('missionnet_event_ids', sa.JSON(), nullable=False),
    sa.Column('sentinel_event_ids', sa.JSON(), nullable=False),
    sa.Column('detection_ids', sa.JSON(), nullable=False),
    sa.Column('incident_ids', sa.JSON(), nullable=False),
    sa.Column('verification', sa.JSON(), nullable=False),
    sa.Column('reset_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_runs')
    # ### end Alembic commands ###
