"""add scenario_id to incidents

Revision ID: 00a78f82f154
Revises: 7ba86ae7b4cf
Create Date: 2026-09-06 15:42:53.282798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '00a78f82f154'
down_revision: Union[str, None] = '7ba86ae7b4cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('scenario_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'scenario_id')
    # ### end Alembic commands ###
