"""phase 8 ingestion adapter status table

Revision ID: 3aeb1cb8824e
Revises: 6f74470e43f5
Create Date: 2026-09-06 23:16:08.393356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3aeb1cb8824e'
down_revision: Union[str, None] = '6f74470e43f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_adapter_status',
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('stream', sa.String(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('source', 'stream')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingestion_adapter_status')
    # ### end Alembic commands ###
