"""phase 5: ai_assessments table

Revision ID: 3f87266014d3
Revises: 00a78f82f154
Create Date: 2026-09-06 18:01:17.031275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3f87266014d3'
down_revision: Union[str, None] = '00a78f82f154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_assessments',
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_provider', sa.String(), nullable=False),
    sa.Column('model_revision', sa.String(), nullable=True),
    sa.Column('model_quantization', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('evidence_pack_hash', sa.String(), nullable=False),
    sa.Column('output_schema_version', sa.String(), nullable=False),
    sa.Column('assessment', sa.JSON(), nullable=True),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('scenario_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_assessments')
    # ### end Alembic commands ###
