"""phase 8 network sensor event fields

Revision ID: 6f74470e43f5
Revises: 99217758d337
Create Date: 2026-09-06 23:03:36.391983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6f74470e43f5'
down_revision: Union[str, None] = '99217758d337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('normalized_events', sa.Column('src_port', sa.Integer(), nullable=True))
    op.add_column('normalized_events', sa.Column('dst_port', sa.Integer(), nullable=True))
    op.add_column('normalized_events', sa.Column('dns_query', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('normalized_events', 'dns_query')
    op.drop_column('normalized_events', 'dst_port')
    op.drop_column('normalized_events', 'src_port')
    # ### end Alembic commands ###
