"""phase 4: incident workflow fields, notes, audit log

Revision ID: 7ba86ae7b4cf
Revises: e98942d9d80d
Create Date: 2026-09-06 15:38:46.097824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7ba86ae7b4cf'
down_revision: Union[str, None] = 'e98942d9d80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('incident_notes',
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.add_column('incidents', sa.Column('disposition', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'resolved_at')
    op.drop_column('incidents', 'disposition')
    op.drop_table('incident_notes')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
