"""phase 6: response_plans table

Revision ID: c5d68cf3e41f
Revises: 3f87266014d3
Create Date: 2026-09-06 19:14:08.771426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c5d68cf3e41f'
down_revision: Union[str, None] = '3f87266014d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_plans',
    sa.Column('response_plan_id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('playbook_id', sa.String(), nullable=False),
    sa.Column('playbook_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('recommendation_source', sa.String(), nullable=False),
    sa.Column('ai_assessment_id', sa.String(), nullable=True),
    sa.Column('policy_bundle_version', sa.String(), nullable=False),
    sa.Column('policy_decision', sa.String(), nullable=False),
    sa.Column('policy_reasons', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('reversible', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.String(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('cancelled_by', sa.String(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scenario_id', sa.String(), nullable=True),
    sa.Column('execution_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ai_assessment_id'], ['ai_assessments.assessment_id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.PrimaryKeyConstraint('response_plan_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response_plans')
    # ### end Alembic commands ###
