"""initial sentinel schema

Revision ID: e8c2c0d03496
Revises: 
Create Date: 2026-09-06 13:31:28.840769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e8c2c0d03496'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('external_asset_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('criticality', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_asset_id')
    )
    op.create_table('detections',
    sa.Column('detection_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('rule_version', sa.String(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('mitre_techniques', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('evidence_summary', sa.String(), nullable=False),
    sa.Column('dedupe_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('detection_id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_table('incidents',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('primary_asset_id', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('mitre_techniques', sa.JSON(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_table('ingestion_cursors',
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('stream', sa.String(), nullable=False),
    sa.Column('last_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('source', 'stream')
    )
    op.create_table('raw_events',
    sa.Column('raw_event_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('raw_event_id')
    )
    op.create_table('incident_detection_links',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('detection_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.detection_id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'detection_id')
    )
    op.create_table('normalized_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_event_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('event_category', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('src_ip', sa.String(), nullable=True),
    sa.Column('dst_ip', sa.String(), nullable=True),
    sa.Column('process_name', sa.String(), nullable=True),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('technique_ids', sa.JSON(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('raw_event_ref', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=True),
    sa.Column('correlation_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['raw_event_ref'], ['raw_events.raw_event_id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('source', 'source_event_id')
    )
    op.create_table('detection_event_links',
    sa.Column('detection_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.detection_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['normalized_events.event_id'], ),
    sa.PrimaryKeyConstraint('detection_id', 'event_id')
    )
    op.create_table('incident_event_links',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['normalized_events.event_id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_event_links')
    op.drop_table('detection_event_links')
    op.drop_table('normalized_events')
    op.drop_table('incident_detection_links')
    op.drop_table('raw_events')
    op.drop_table('ingestion_cursors')
    op.drop_table('incidents')
    op.drop_table('detections')
    op.drop_table('assets')
    # ### end Alembic commands ###
