"""add correlation_key to detections and incidents

Revision ID: e98942d9d80d
Revises: e8c2c0d03496
Create Date: 2026-09-06 13:36:10.821997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e98942d9d80d'
down_revision: Union[str, None] = 'e8c2c0d03496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('correlation_key', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('correlation_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'correlation_key')
    op.drop_column('detections', 'correlation_key')
    # ### end Alembic commands ###
