"""add synthetic_password to identity_users

Revision ID: ae25b1ea2ef9
Revises: f13ca6155653
Create Date: 2026-09-06 13:26:48.475633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ae25b1ea2ef9'
down_revision: Union[str, None] = 'f13ca6155653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'identity_users',
        sa.Column(
            'synthetic_password', sa.String(), nullable=False, server_default='SynthLab#2026'
        ),
    )
    op.alter_column('identity_users', 'synthetic_password', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identity_users', 'synthetic_password')
    # ### end Alembic commands ###
