"""initial missionnet schema

Revision ID: f13ca6155653
Revises: 
Create Date: 2026-09-06 13:04:36.696734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f13ca6155653'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('mission_role', sa.String(), nullable=False),
    sa.Column('criticality', sa.Integer(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.Column('max_allowed_outage_seconds', sa.Integer(), nullable=False),
    sa.Column('containment_cost', sa.String(), nullable=False),
    sa.Column('rollback_supported', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('network_state', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('audit_events',
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('identity_users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('mission_records',
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['identity_users.user_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('service_tokens',
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('classification', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['identity_users.user_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('telemetry_samples',
    sa.Column('sample_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('battery', sa.Integer(), nullable=False),
    sa.Column('link_quality', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.PrimaryKeyConstraint('sample_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry_samples')
    op.drop_table('service_tokens')
    op.drop_table('mission_records')
    op.drop_table('identity_users')
    op.drop_table('audit_events')
    op.drop_table('assets')
    # ### end Alembic commands ###
